export const demoOptions = {
  brands: [
    { value: "strauss", label: "Strauss" },
    { value: "rhone", label: "Rhone" },
    { value: "arcteryx", label: "Arc'teryx" },
  ],
  audiences: [
    { value: "men", label: "Men" },
    { value: "women", label: "Women" },
    { value: "kids", label: "Kids" },
    { value: "footwear", label: "Footwear" },
    { value: "gear-accessories", label: "Gear & Accessories" },
  ],
  collections: [
    "e.s.ambition",
    "e.s.basics",
    "e.s.concrete",
    "e.s.e:pic",
    "e.s.iconic",
    "e.s.motion",
    "e.s.motion 2020",
    "e.s.motion ten",
    "e.s.t:aktik",
    "e.s.trail",
    "e.s.vintage",
    "Strauss x 1620",
    "Strauss x LA FC",
    "Strauss x Stuntmen's Association",
  ],
  categories: [
    "Shirts",
    "Pants",
    "Footwear",
    "Outerwear",
    "Hoodies & Sweatshirts",
    "Tool Bags",
    "Shorts",
    "Hats & Beanies",
    "Gloves",
    "Tool Belts",
    "Socks",
    "Knee Pads",
    "Leggings",
    "Thermal Layers",
    "Belts",
    "Glasses",
    "Backpacks & Bags",
  ],
  subcategories: [
    "T-Shirts",
    "Polos",
    "Long Sleeves",
    "Work Shirts",
    "High-Vis Shirts",
    "Kids Shirts",
    "Work Pants",
    "Cargo Pants",
    "Double-Front Pants",
    "Jeans",
    "Bibs, Coveralls & Overalls",
    "Kids Pants",
    "Work Shorts",
    "Cargo Shorts",
    "Women's Shorts",
    "Softshell Jackets",
    "Lightweight Jackets",
    "Winter Jackets",
    "Work Jackets",
    "Vests",
    "High-Vis Outerwear",
    "Kids Jackets",
    "Hoodies",
    "Crewnecks",
    "Full-Zip Sweatshirts",
    "Women's Hoodies & Sweatshirts",
    "Safety Sneakers",
    "Safety-Toe Boots",
    "Soft-Toe Boots",
    "Waterproof Boots & Shoes",
    "Work Boots",
    "Work Shoes",
    "Men's Thermal Layers",
    "Women's Thermal Layers",
    "Tool Storage",
    "Headwear",
    "Work Gloves",
    "Tool Belts",
    "Work Socks",
    "Knee Protection",
    "Women's Leggings",
    "Work Belts",
    "Safety Glasses",
    "Backpacks & Bags",
  ],
  price: { min: 0, max: 350 },
};

export const demoDashboard = {
  source: [
    "https://us.strauss.com",
    "https://www.rhone.com",
    "https://arcteryx.com/us/en",
  ],
  scraped_at: null,
  summary: {
    total_products: 572,
    brands: 3,
    categories: 19,
    average_price: 84.2,
    available_products: 498,
    collection_memberships: 294,
    named_collection_products: 290,
    unassigned_collection_products: 163,
    multi_collection_products: 4,
    overlap_memberships: 4,
    category_memberships: 590,
    multi_category_products: 18,
    category_overlap_memberships: 18,
    availability_rate: 87.1,
  },
  audiences: [
    { name: "Men", value: 319 },
    { name: "Footwear", value: 95 },
    { name: "Gear & Accessories", value: 79 },
    { name: "Women", value: 57 },
    { name: "Kids", value: 31 },
  ],
  collections: [
    { name: "e.s.e:pic", value: 67 },
    { name: "e.s.iconic", value: 47 },
    { name: "e.s.basics", value: 45 },
    { name: "e.s.trail", value: 29 },
    { name: "e.s.vintage", value: 26 },
    { name: "e.s.t:aktik", value: 23 },
    { name: "e.s.motion ten", value: 17 },
    { name: "e.s.concrete", value: 11 },
    { name: "e.s.motion 2020", value: 9 },
    { name: "e.s.motion", value: 3 },
    { name: "e.s.ambition", value: 1 },
  ],
  categories: [
    { name: "Shirts", value: 146 },
    { name: "Pants", value: 106 },
    { name: "Footwear", value: 95 },
    { name: "Outerwear", value: 65 },
    { name: "Hoodies & Sweatshirts", value: 38 },
    { name: "Tool Bags", value: 24 },
    { name: "Shorts", value: 23 },
    { name: "Hats & Beanies", value: 17 },
    { name: "Gloves", value: 14 },
    { name: "Overalls, Bib & Coveralls", value: 12 },
  ],
  products: [],
};
