export const demoOptions = {
  brands: [
    { value: "strauss", label: "Strauss" },
    { value: "rhone", label: "Rhone" },
    { value: "arcteryx", label: "Arc'teryx" },
  ],
  audiences: [
    { value: "men", label: "Men" },
    { value: "women", label: "Women" },
    { value: "kids", label: "Kids" },
    { value: "footwear", label: "Footwear" },
    { value: "gear-accessories", label: "Gear & Accessories" },
  ],
  categories: [
    "Shirts",
    "Pants",
    "Footwear",
    "Outerwear",
    "Hoodies & Sweatshirts",
    "Tool Bags",
    "Shorts",
    "Hats & Beanies",
    "Gloves",
    "Overalls, Bib & Coveralls",
  ],
  price: { min: 0, max: 350 },
};

export const demoDashboard = {
  source: [
    "https://us.strauss.com",
    "https://www.rhone.com",
    "https://arcteryx.com/us/en",
  ],
  scraped_at: null,
  summary: {
    total_products: 572,
    brands: 3,
    categories: 19,
    average_price: 84.2,
    available_products: 498,
    collection_memberships: 581,
    multi_collection_products: 9,
    overlap_memberships: 9,
    category_memberships: 590,
    multi_category_products: 18,
    category_overlap_memberships: 18,
    availability_rate: 87.1,
  },
  audiences: [
    { name: "Men", value: 319 },
    { name: "Footwear", value: 95 },
    { name: "Gear & Accessories", value: 79 },
    { name: "Women", value: 57 },
    { name: "Kids", value: 31 },
  ],
  categories: [
    { name: "Shirts", value: 146 },
    { name: "Pants", value: 106 },
    { name: "Footwear", value: 95 },
    { name: "Outerwear", value: 65 },
    { name: "Hoodies & Sweatshirts", value: 38 },
    { name: "Tool Bags", value: 24 },
    { name: "Shorts", value: 23 },
    { name: "Hats & Beanies", value: 17 },
    { name: "Gloves", value: 14 },
    { name: "Overalls, Bib & Coveralls", value: 12 },
  ],
  products: [],
};
